#!/bin/bash

commit_regex='^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}$'

if ! grep -E "$commit_regex" "$1"; then
  echo "Aborting commit. Your commit message is invalid."
  exit 1
fi
