#!/bin/bash

COMMIT_REGEX='^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}$'

if ! grep -E "$COMMIT_REGEX" "$1"; then
  echo "Aborting commit. Your commit message is invalid."
  exit 1
fi
