name: Coptit Bot CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  lint:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "19.x"
    - run: npm ci
    - run: npm run lint

  format:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: "19.x"
    - run: npm ci
    - run: npm run format
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Format code"
        branch: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker image build -t kunalsin9h/coptit-bot:latest .
    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "kunalsin9h" --password-stdin
        docker push kunalsin9h/coptit-bot:latest
